# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# TODO: Remove existing warnings in the Sphinx build, then uncomment the following
# sphinx:
#   fail_on_warning: true

build:
  os: ubuntu-20.04
  tools:
    python: '3'
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH python -m poetry install
