# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

services:
  - postgresql

env:
  global : DATABASE_URL=postgres://postgres:@127.0.0.1:5432

matrix:
    include:
      # Python version is just for the look on travis.
        - python: 2.7
          env: TOX_ENV=py27-django111

        - python: 3.5
          env: TOX_ENV=py35-django111

        - python: 3.6
          env: TOX_ENV=py36-django111

        - python: 3.7
          env: TOX_ENV=py37-django111

        - python: 3.5
          env: TOX_ENV=py35-django20

        - python: 3.6
          env: TOX_ENV=py36-django20

        - python: 3.7
          env: TOX_ENV=py37-django20

        - python: 3.5
          env: TOX_ENV=py35-django21

        - python: 3.6
          env: TOX_ENV=py36-django21

        - python: 3.7
          env: TOX_ENV=py37-django21

        - python: 3.5
          env: TOX_ENV=py35-django22

        - python: 3.6
          env: TOX_ENV=py36-django22

        - python: 3.7
          env: TOX_ENV=py37-django22

        - python: 3.5
          env: TOX_ENV=py35-djangostable

        - python: 3.6
          env: TOX_ENV=py36-djangostable

        - python: 3.7
          env: TOX_ENV=py37-djangostable

        - env: TOX_ENV=linters

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
