name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: |
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-ci
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: success

      - name: Exit if CI did not succeed
        if: steps.wait-for-ci.outputs.conclusion != 'success'
        run: exit 1

      - name: Publish on PyPI
        run: poetry publish --no-interaction --build --username "__token__" --password "$PYPI_TOKEN"
        env:
          PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"
